# -*- coding: utf-8 -*-
"""Chatbot v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBqCBWsGSsOExA1wGK3xPdmGJwwpodf-
"""

!pip install tenacity
#CHATBOT QUE RECUERDA Y REINTENTA CUANDO EL SERVIDOR FALLA version 1
from google import genai
from tenacity import retry, stop_after_attempt, wait_fixed, retry_if_exception_type
import time

client = genai.Client(api_key="GEMINI_API_KEY")

@retry(
    stop=stop_after_attempt(3),        # máximo 3 intentos
    wait=wait_fixed(5),                # espera 5 segundos entre intentos
    retry=retry_if_exception_type(Exception),
    reraise=True                       # si falla los 3, lanza el error
)
def preguntar_ia(historial):
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=historial
    )
    return response.text

# --- Chatbot ---
# Define PERSONALIDAD before it's used in historial initialization
PERSONALIDAD = """Eres Sofia, asistente virtual de la Clínica Estética Bella Lima.
Ubicados en Miraflores, Lima.

Servicios y precios:
- Limpieza facial: S/. 80
- Botox: S/. 350
- Consulta dermatológica: S/. 120

Horarios: Lunes a Sábado de 9am a 7pm

Cuando alguien quiera agendar una cita:
1. Pregunta su nombre
2. Pregunta qué servicio desea
3. Pregunta qué día y hora prefiere
4. Confirma la cita con todos los datos

Siempre responde en español, sé amable y profesional.
"""

historial = [{"role": "user", "parts": [{"text": PERSONALIDAD}]},
             {"role": "model", "parts": [{"text": "Entendido, seré Sofia de Clínica Bella Lima."}]}]
print("🤖 Chatbot listo. Escribe 'salir' para terminar.\n")

while True:
    mensaje = input("Tú: ")

    if mensaje.lower() == "salir":
        print("Bot: ¡Hasta luego! 👋")
        break

    historial.append({"role": "user", "parts": [{"text": mensaje}]})

    try:
        respuesta = preguntar_ia(historial)
    except Exception:
        respuesta = "❌ Servidor caído. Intenta en unos minutos."

    historial.append({"role": "model", "parts": [{"text": respuesta}]})
    print(f"Bot: {respuesta}\n")

!pip install gspread google-auth -q
#CHATBOT QUE RECUERDA Y REINTENTA CUANDO EL SERVIDOR FALLA, RESERVA Y ACTUALIZA EN GOOGLE SHEETS
from google import genai
from tenacity import retry, stop_after_attempt, wait_fixed, retry_if_exception_type
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime

# ── Gemini ──────────────────────────────────────
client = genai.Client(api_key="GEMINI_API_KEY")

# ── Google Sheets ────────────────────────────────
SCOPES = ["https://spreadsheets.google.com/feeds",
          "https://www.googleapis.com/auth/drive"]

creds = Credentials.from_service_account_file(
    "/content/gen-lang-client-0246289414-c2ff401f463d.json",  # ✅ tu archivo
    scopes=SCOPES
)
gc = gspread.authorize(creds)
sheet = gc.open_by_url("https://docs.google.com/spreadsheets/d/1DMeZpeq97TRROi9hpUzXFFBt0gAzYOCcGxhI9aiVWII/edit?gid=0#gid=0").sheet1

def guardar_cita(nombre, servicio, fecha, hora, total):
    sheet.append_row([nombre, servicio, fecha, hora, total,
                      datetime.now().strftime("%d/%m/%Y %H:%M")])
    print("✅ Cita guardada en Google Sheets!")

@retry(
    stop=stop_after_attempt(3),
    wait=wait_fixed(5),
    retry=retry_if_exception_type(Exception),
    reraise=True
)
def preguntar_ia(historial):
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=historial
    )
    return response.text

PERSONALIDAD = """
Eres Sofia, asistente virtual de Clinica Estetica Bella Lima.
Ubicados en Miraflores, Lima.

Servicios y precios:
- Limpieza facial: S/. 80
- Botox: S/. 350
- Consulta dermatologica: S/. 120

Horarios: Lunes a Sabado de 9am a 7pm

Cuando confirmes una cita, escribe EXACTAMENTE este formato al final:
CITA_CONFIRMADA|nombre|servicio|fecha|hora|total

Ejemplo:
CITA_CONFIRMADA|Maria Garcia|Botox|Sabado|5:00pm|S/.350
"""

historial = [
    {"role": "user", "parts": [{"text": PERSONALIDAD}]},
    {"role": "model", "parts": [{"text": "Entendido, sere Sofia de Clinica Bella Lima."}]}
]

print("🤖 Sofia - Clinica Bella Lima\n")

while True:
    mensaje = input("Tú: ")

    if mensaje.lower() == "salir":
        print("Sofia: ¡Hasta luego! 👋")
        break

    historial.append({"role": "user", "parts": [{"text": mensaje}]})

    try:
        respuesta = preguntar_ia(historial)
    except Exception:
        respuesta = "❌ Error de conexion. Intenta en unos minutos."

    # Detectar cita confirmada y guardar
    if "CITA_CONFIRMADA" in respuesta:
        try:
            linea = [l for l in respuesta.split("\n") if "CITA_CONFIRMADA" in l][0]
            _, nombre, servicio, fecha, hora, total = linea.split("|")
            guardar_cita(nombre.strip(), servicio.strip(),
                        fecha.strip(), hora.strip(), total.strip())
            # 👇 Limpia mejor la respuesta
            respuesta = respuesta.replace(linea, "").replace("\n\n\n", "\n").strip()
        except:
            pass


    historial.append({"role": "model", "parts": [{"text": respuesta}]})
    print(f"\nSofia: {respuesta}\n")

